
#define GPIO_I2C_CLK				95
#define GPIO_I2C_DAT				96
#define HTCLEO_GPIO_UP_INT_N		90
#define HTCLEO_GPIO_UP_RESET_N		91
#define HTCLEO_GPIO_LS_EN_N			119
#define DS2746_I2C_SLAVE_ADDR		0x26

#define MSM_PANEL_PHYS        		0x00080000
/* Display */
#define HTCLEO_GPIO_LCM_POWER		88
#define HTCLEO_GPIO_LCM_RESET		29
#define HTCLEO_LCD_R1				(114)
#define HTCLEO_LCD_R2				(115)
#define HTCLEO_LCD_R3				(116)
#define HTCLEO_LCD_R4				(117)
#define HTCLEO_LCD_R5				(118)
#define HTCLEO_LCD_G0				(121)
#define HTCLEO_LCD_G1				(122)
#define HTCLEO_LCD_G2				(123)
#define HTCLEO_LCD_G3				(124)
#define HTCLEO_LCD_G4				(125)
#define HTCLEO_LCD_G5				(126)
#define HTCLEO_LCD_B1				(130)
#define HTCLEO_LCD_B2				(131)
#define HTCLEO_LCD_B3				(132)
#define HTCLEO_LCD_B4				(133)
#define HTCLEO_LCD_B5				(134)
#define HTCLEO_LCD_PCLK	       		(135)
#define HTCLEO_LCD_VSYNC	      	(136)
#define HTCLEO_LCD_HSYNC			(137)
#define HTCLEO_LCD_DE				(138)

/* Touchscreen */
#define HTCLEO_GPIO_TS_POWER			160
#define HTCLEO_GPIO_TS_IRQ      		92
#define HTCLEO_GPIO_TS_SEL      		108
#define HTCLEO_GPIO_TS_MULT				82

#define HTCLEO_GPIO_H2W_CLK				27
#define HTCLEO_GPIO_LED_3V3_EN			85
#define HTCLEO_GPIO_KP_MKOUT0    		33
#define HTCLEO_GPIO_KP_MKOUT1    		32
#define HTCLEO_GPIO_KP_MKOUT2    		31
#define HTCLEO_GPIO_KP_MPIN0     		42
#define HTCLEO_GPIO_KP_MPIN1     		41
#define HTCLEO_GPIO_KP_MPIN2     		40
#define HTCLEO_GPIO_KP_LED	 			48
#define HTCLEO_GPIO_POWER_KEY			94
#define HTCLEO_GPIO_VIBRATOR_ON        	100
#define HTCLEO_GPIO_FLASHLIGHT_TORCH   	143

/* Battery */
#define HTCLEO_GPIO_BATTERY_CHARGER_ENABLE	22
#define HTCLEO_GPIO_BATTERY_CHARGER_CURRENT	16
#define HTCLEO_GPIO_BATTERY_OVER_CHG		147
#define HTCLEO_GPIO_POWER_USB     			109
#define HTCLEO_GPIO_USBPHY_3V3_ENABLE		104